# Generated by Django 6.0.7 on 2026-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('options', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Science', 'Science'), ('Sports', 'Sports'), ('History', 'History')], max_length=200)),
                ('different_levels', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=200)),
            ],
        ),
    ]
