# Generated by Django 6.0.7 on 2026-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='options',
            new_name='option_a',
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_b',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_c',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_d',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
